name: Indie_game
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Pytest
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - name: Push to main
        run: |
          git push

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ 741900014 }}
          token: ${{ 7125960904:AAGHx3gjvIWWIMjEUk1oZlEAF--J0nVKJWc }}
          message: ${{ github.workflow }} успешно выполнен!
