name: Indie_game
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r indie_game_service/requirements.txt
      - name: Test with Pytest
        run: python -m pytest indie_game_service/tests/

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - name: Push to main
        run: |
          git push

  send_message:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: send message v1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_1 }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
      - name: send message v2
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_2 }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
