name: Indie_game
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl --data chat_id=${{ secrets.TELEGRAM_TO_1 }} --data-urlencode "text=Новый коммит в репозиторий! ${{ github.repository }}" "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage"
